# Generated by Django 3.2.25 on 2024-07-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_phonelogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonelogin',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
