# Generated by Django 3.2.25 on 2024-07-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_fingerprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fingerprint',
            name='finger_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fingerprint',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
