# Generated by Django 3.2.25 on 2024-07-31 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20240720_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='fingerprint',
            name='action_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
