# Generated by Django 3.2.25 on 2024-08-14 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20240814_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicefinger',
            old_name='device_mac_id',
            new_name='mac_id',
        ),
    ]
