# Generated by Django 3.2.25 on 2024-08-14 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_device_mac_id_devicefinger_mac_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicelog',
            old_name='user_device_id',
            new_name='user_device',
        ),
        migrations.RenameField(
            model_name='userdevice',
            old_name='device_id',
            new_name='device',
        ),
        migrations.RemoveField(
            model_name='userdevice',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userdevice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userfinger'),
        ),
    ]
