# Generated by Django 3.2.25 on 2024-08-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20240814_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicefinger',
            name='is_for_door',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='devicefinger',
            name='static_ip',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='devicelog',
            name='is_open',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='door_ip',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
