# Generated by Django 3.2.25 on 2024-10-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_temprature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temprature',
            name='humidity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='temprature',
            name='temprature',
            field=models.FloatField(),
        ),
    ]
