# Generated by Django 5.0.9 on 2024-11-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20241021_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='authoritative',
            field=models.BooleanField(blank=True, default=1, null=True),
        ),
    ]
