# Generated by Django 5.0.9 on 2024-11-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_userdevice_authoritative'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicefinger',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
