# Generated by Django 5.0.9 on 2024-11-24 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_devicefinger_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfinger',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fingers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
