# Generated by Django 5.0.9 on 2024-11-25 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_userfinger_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='temprature',
            name='action_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='authoritative',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
