# Generated by Django 5.0.9 on 2024-12-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_userdevice_user_user_employee_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='employee_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='employee_code',
            field=models.IntegerField(null=True),
        ),
    ]
