# Generated by Django 5.0.9 on 2025-04-12 07:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_user_employee_code_remove_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(1), to=settings.AUTH_USER_MODEL),
        ),
    ]
